var tweets = [

    //Motivational tweets
    "If you set your goals ridiculously high and it's a failure, you will fail above everyone else’s success.",
"I don’t want to get to the end of my life and find that I lived just the length of it. I want to have lived the width of it as well.",
"Motivation is what gets you started. Habit is what keeps you going.",
"Our greatest fear should not be of failure … but of succeeding at things in life that don’t really matter.",
"Success usually comes to those who are too busy to be looking for it.",
"Things work out best for those who make the best of how things work out.",
"Entrepreneurs average 3.8 failures before final success. What sets the successful ones apart is their amazing persistence.",
"In my experience, there is only one motivation, and that is desire. No reasons or principle contain it or stand against it.",
"Stop chasing the money and start chasing the passion.",
"All our dreams can come true if we have the courage to pursue them.",
"If you are willing to do more than you are paid to do, eventually you will be paid to do more than you do.",
"You can’t connect the dots looking forward; you can only connect them looking backward. So you have to trust that the dots will somehow connect in your future. You have to trust in something–your gut, destiny, life, karma, whatever. This approach has never let me down, and it has made all the difference in my life.",
"Success is walking from failure to failure with no loss of enthusiasm.",
"Whenever you see a successful person, you only see the public glories, never the private sacrifices to reach them.",
"Success? I don’t know what that word means. I’m happy. But success, that goes back to what in somebody’s eyes success means. For me, success is inner peace. That’s a good day for me.",
"The successful warrior is the average man, with laserlike focus.",
"Keep on going, and the chances are that you will stumble on something, perhaps when you are least expecting it. I have never heard of anyone ever stumbling on something sitting down.",
"If you genuinely want something, don’t wait for it–teach yourself to be impatient.",
"Opportunities don’t happen. You create them.",
"Try not to become a person of success, but rather try to become a person of value.",
"It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change.",
"Twenty years from now, you will be more disappointed by the things that you didn’t do than by the ones you did do. So throw off the bowlines. Sail away from the safe harbor. Catch the trade winds in your sails. Explore. Dream. Discover.",
"The first step toward success is taken when you refuse to be a captive of the environment in which you first find yourself.",
"Whenever you find yourself on the side of the majority, it is time to pause and reflect.",
"Great minds discuss ideas; average minds discuss events; small minds discuss people.",
"The best revenge is massive success.",
"I have not failed. I’ve just found 10,000 ways that won’t work.",
"A successful man is one who can lay a firm foundation with the bricks others have thrown at him.",
"I don’t know the key to success, but the key to failure is trying to please everyone.",
"Though no one can go back and make a brand-new start, anyone can start from now and make a brand-new ending.",
"I find that when you have a real interest in life and a curious life, that sleep is not the most important thing.",
"No one can make you feel inferior without your consent.",
"The whole secret of a successful life is to find out what is one’s destiny to do, and then do it.",
"The distance between insanity and genius is measured only by success.",
"All progress takes place outside the comfort zone.",
"You may only succeed if you desire succeeding; you may only fail if you do not mind failing.",
"Courage is resistance to fear, mastery of fear–not absence of fear.",
"Don’t be afraid to give up the good to go for the great.",
"Happiness is a butterfly, which when pursued, is always beyond your grasp, but which, if you will sit down quietly, may alight upon you.",
"Success is the sum of small efforts, repeated day in and day out.",
"If you want to achieve excellence, you can get there today. As of this second, quit doing less-than-excellent work.",
"If you can’t explain it simply, you don’t understand it well enough.",
"There are two types of people who will tell you that you cannot make a difference in this world: those who are afraid to try and those who are afraid you will succeed.",
"Start where you are. Use what you have. Do what you can.",
"I find that the harder I work, the more luck I seem to have.",
"The starting point of all achievement is desire.",
"People ask, ‘What’s the best role you’ve ever played?’ The next one.",


];
